[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "./spec/x86_64-lateral.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
